version: "3.8"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
            args:
                - NODE_ENV=production # Change this to 'development' as needed
        ports:
            - "3033:3000"
        depends_on:
            - backend
        environment:
            - API_BASE_URL=http://backend:8080
            - NODE_ENV=production

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "8089:8080"
        depends_on:
            - mongodb
        volumes:
            - .:/rest-api
            - node_modules:/rest-api/node_modules/
        environment:
            - OPENAI_API_KEY=REPLACE_WITH_REAL_OPENAI_API_KEY
            - MONGODB_URI=mongodb://mongodb:27017
            - CHOKIDAR_USEPOLLING=true

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
    node_modules:
